'''Pydantic Schemas for request and response body structure and validation'''
from typing import Optional
from pydantic import BaseModel, Field

class NoteCreate(BaseModel):
    '''Schema for creating a new note (title & content only needed; date=autogenerated)'''
    title: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description='Title of the note')
    content: str = Field(
        ...,
        min_length=1,
        description='Content of the note')

class NoteUpdate(BaseModel):
    '''Schema for updating a note'''
    title: Optional[str] = Field(
        None, min_length=1,
        max_length=100,
        description='New title of the note')
    content: Optional[str] = Field(
        None,
        min_length=1,
        description='New updated content')

class NoteResponse(BaseModel):
    '''Schema for API response which includes all note fields'''
    id: int = Field(..., description='Note\'s unique identifier')
    title: str = Field(..., description='Title of the note')
    content: str = Field(..., description='Content of the note')
    created_at: str = Field(..., description='Date the note was created in standard ISO Format')
